// <auto-generated />
using System;
using AbbouClima.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AbbouClima.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250103194149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AbbouClima.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Borrado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Correo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaModificacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AbbouClima.Models.Presupuesto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Cantidad1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad10")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad5")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad6")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad7")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad8")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Cantidad9")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion10")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion2")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion3")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion4")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion5")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion6")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion7")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion9")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enviado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ImporteTotal")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeIVA")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NºPresupuesto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Precio1")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio10")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio2")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio3")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio4")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio5")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio6")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio7")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio8")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Precio9")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Validez")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("AbbouClima.Models.Presupuesto", b =>
                {
                    b.HasOne("AbbouClima.Models.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AbbouClima.Models.Cliente", b =>
                {
                    b.Navigation("Presupuestos");
                });
#pragma warning restore 612, 618
        }
    }
}
